### ISSUE TITLE
Problem with running on linux?

### ISSUE THREAD

**Issue by IronClawTrem** [lavacord/discord.js#68]
I was running a discord bot with this just fine on Windows using Node.js version 14, and I've now switched to my Linux PC and tried running the same code again, with the same version of Node.js, and I get this error:

/home/luu/LuuBot/node_modules/lavacord/dist/lib/Manager.js:25
        for (const node of nodes)
                           ^

TypeError: nodes is not iterable
    at new Manager (/home/luu/LuuBot/node_modules/lavacord/dist/lib/Manager.js:25:28)
    at new Manager (/home/luu/LuuBot/node_modules/@lavacord/discord.js/dist/index.js:18:9)
    at Object.<anonymous> (/home/luu/LuuBot/index.js:7:25)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by IronClawTrem** [comment]
Reinstalled the package and it seems to work, no idea why.
